# Generated by Django 5.2.4 on 2025-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.CharField(max_length=100),
        ),
    ]
