# Generated by Django 5.2.4 on 2025-07-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0002_alter_ride_customer_alter_ride_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='source',
            new_name='destination_source',
        ),
    ]
