# Generated by Django 5.2.4 on 2025-07-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0003_rename_source_ride_destination_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_status',
        ),
    ]
