# Generated by Django 5.2.4 on 2025-07-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0004_remove_ride_fare_remove_ride_ride_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.AddField(
            model_name='ride',
            name='Vehicle',
            field=models.CharField(default='Car', max_length=50),
        ),
    ]
