# Generated by Django 5.2.4 on 2025-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0005_remove_ride_driver_ride_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='Vehicle',
        ),
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='fare',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
