# Generated by Django 5.2.4 on 2025-07-17 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0006_remove_vehicle_driver_remove_ride_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberapp.customer'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(choices=[('kayamkulam', 'kayamkulam'), ('karunagapally', 'karunagapally'), ('ernakulam', 'ernakulam'), ('oachira', 'oachira')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination_source',
            field=models.CharField(choices=[('kayamkulam', 'kayamkulam'), ('karunagapally', 'karunagapally'), ('ernakulam', 'ernakulam'), ('oachira', 'oachira')], max_length=100),
        ),
    ]
