# Generated by Django 5.2.4 on 2025-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0007_alter_ride_customer_alter_ride_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(choices=[('kayamkulam', 'Kayamkulam'), ('karunagapally', 'Karunagapally'), ('ernakulam', 'Ernakulam'), ('oachira', 'Oachira')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination_source',
            field=models.CharField(choices=[('kayamkulam', 'Kayamkulam'), ('karunagapally', 'Karunagapally'), ('ernakulam', 'Ernakulam'), ('oachira', 'Oachira')], max_length=100),
        ),
    ]
