# Generated by Django 5.2.4 on 2025-07-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0008_alter_ride_destination_alter_ride_destination_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='customer',
            field=models.CharField(choices=[('kayamkulam', 'Kayamkulam'), ('karunagapally', 'Karunagapally'), ('ernakulam', 'Ernakulam'), ('oachira', 'Oachira')], max_length=100),
        ),
    ]
