# Generated by Django 5.2.4 on 2025-07-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0009_alter_ride_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberapp.customer'),
        ),
    ]
