# Generated by Django 5.2.4 on 2025-07-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0010_alter_ride_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='customer',
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(choices=[('kayamkulam', 'Kayamkulam'), ('alappuzha', 'alappuzha'), ('ernakulam', 'Ernakulam'), ('thrissur', 'thrissur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination_source',
            field=models.CharField(choices=[('kayamkulam', 'Kayamkulam'), ('alappuzha', 'alappuzha'), ('ernakulam', 'Ernakulam'), ('thrissur', 'thrissur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
