# Generated by Django 5.2.4 on 2025-07-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberapp', '0011_remove_ride_customer_alter_ride_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='fare',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
